In [1]:
import pandas as pd

In [102]:
mvps = pd.read_csv("mvps.csv")

In [103]:
mvps

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,0,1,Michael Jordan,27,CHI,77,891,960,0.928,82,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,1,2,Magic Johnson,31,LAL,10,497,960,0.518,79,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,2,3,David Robinson,25,SAS,6,476,960,0.496,82,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,3,4,Charles Barkley,27,PHI,2,222,960,0.231,67,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,4,5,Karl Malone,27,UTA,0,142,960,0.148,82,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,4,5,Jalen Brunson,27,NYK,0,142,990,0.143,77,...,3.6,6.7,0.9,0.2,0.479,0.401,0.847,11.2,0.198,2024
504,5,6,Jayson Tatum,25,BOS,0,86,990,0.087,74,...,8.1,4.9,1.0,0.6,0.471,0.376,0.833,10.4,0.189,2024
505,6,7,Anthony Edwards,22,MIN,0,18,990,0.018,79,...,5.4,5.1,1.3,0.5,0.461,0.357,0.836,7.5,0.130,2024
506,7,8,Domantas Sabonis,27,SAC,0,3,990,0.003,82,...,13.7,8.2,0.9,0.6,0.594,0.379,0.704,12.6,0.206,2024
507,8,9,Kevin Durant,35,PHO,0,1,990,0.001,75,...,6.6,5.0,0.9,1.2,0.523,0.413,0.856,8.3,0.142,2024

In [104]:
mvps = mvps[["Player", "Year", "Pts Won", "Pts Max", "Share"]]

In [105]:
mvps

               Player  Year  Pts Won  Pts Max  Share
0      Michael Jordan  1991      891      960  0.928
1       Magic Johnson  1991      497      960  0.518
2      David Robinson  1991      476      960  0.496
3     Charles Barkley  1991      222      960  0.231
4         Karl Malone  1991      142      960  0.148
..                ...   ...      ...      ...    ...
503     Jalen Brunson  2024      142      990  0.143
504      Jayson Tatum  2024       86      990  0.087
505   Anthony Edwards  2024       18      990  0.018
506  Domantas Sabonis  2024        3      990  0.003
507      Kevin Durant  2024        1      990  0.001

[508 rows x 5 columns]

In [287]:
players = pd.read_csv("players.csv")

In [288]:
players

,Unnamed: 0,Rk,Player,Age,Team,Pos,G,GS,MP,FG,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year
0,0,1,Michael Jordan,27,CHI,SG,82,82,37.0,12.1,...,4.6,6.0,5.5,2.7,1.0,2.5,2.8,31.5,"MVP-1,DPOY-7,AS,NBA1,DEF1",1991
1,1,2,Karl Malone,27,UTA,PF,82,82,40.3,10.3,...,8.9,11.8,3.3,1.1,1.0,3.0,3.3,29.0,"MVP-5,AS,NBA1",1991
2,2,3,Bernard King,34,WSB,SF,64,64,37.5,11.1,...,3.2,5.0,4.6,0.9,0.3,4.0,2.9,28.4,"MVP-16,AS,NBA3",1991
3,3,4,Charles Barkley,27,PHI,SF,67,67,37.3,9.9,...,6.3,10.1,4.2,1.6,0.5,3.1,2.6,27.6,"MVP-4,AS,NBA1",1991
4,4,5,Patrick Ewing,28,NYK,C,81,81,38.3,10.4,...,8.8,11.2,3.0,1.0,3.2,3.6,3.5,26.6,"MVP-11,DPOY-7,AS,NBA2",1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20342,730,565,Riley Minix,24,SAS,SF,1,0,7.0,0.0,...,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2025
20343,731,566,Jahlil Okafor,29,IND,C,1,0,3.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,2025
20344,732,567,Zyon Pullin,23,MEM,SG,3,0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2025
20345,733,568,Isaiah Stevens,24,MIA,PG,3,0,2.0,0.0,...,0.7,0.7,0.0,0.3,0.0,0.0,0.0,0.0,NaN,2025
20346,734,569,Terry Taylor,25,SAC,PF,3,0,2.0,0.0,...,0.0,0.3,0.7,0.0,0.0,0.0,0.0,0.0,NaN,2025

In [289]:
del players["Unnamed: 0"]
del players["Rk"]
del players["Awards"]

In [290]:
players.head()

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Michael Jordan,27,CHI,SG,82,82,37.0,12.1,22.4,0.539,...,1.4,4.6,6.0,5.5,2.7,1.0,2.5,2.8,31.5,1991
1,Karl Malone,27,UTA,PF,82,82,40.3,10.3,19.6,0.527,...,2.9,8.9,11.8,3.3,1.1,1.0,3.0,3.3,29.0,1991
2,Bernard King,34,WSB,SF,64,64,37.5,11.1,23.6,0.472,...,1.8,3.2,5.0,4.6,0.9,0.3,4.0,2.9,28.4,1991
3,Charles Barkley,27,PHI,SF,67,67,37.3,9.9,17.4,0.570,...,3.9,6.3,10.1,4.2,1.6,0.5,3.1,2.6,27.6,1991
4,Patrick Ewing,28,NYK,C,81,81,38.3,10.4,20.3,0.514,...,2.4,8.8,11.2,3.0,1.0,3.2,3.6,3.5,26.6,1991

In [291]:
players["Player"] = players["Player"].str.replace("*","", regex=False)

In [292]:
players.groupby(["Player", "Year"])

In [293]:
def single_row(df):
    if df.shape[0] == 1:
        return df
    
    row = df.iloc[[0]].copy()
    last_team = df.iloc[-1]["Team"]
    row.loc[:, "Team"] = last_team
    return row

players = players.groupby(["Player", "Year"]).apply(single_row)

In [294]:
players.head(20)

                                 Player  Age Team Pos   G  GS    MP   FG  \
Player        Year
A.C. Green    1991 178       A.C. Green   27  LAL  PF  82  21  26.4  3.1
              1992 534       A.C. Green   28  LAL  PF  82  53  35.4  4.7
              1993 1004      A.C. Green   29  LAL  PF  82  55  34.4  4.6
              1994 1421      A.C. Green   30  PHO  PF  82  55  34.5  5.7
              1995 1960      A.C. Green   31  PHO  SF  82  52  32.8  3.8
              1996 2522      A.C. Green   32  PHO  SF  82  36  25.8  2.6
              1997 3051      A.C. Green   33  DAL  PF  83  73  30.0  2.8
              1998 3644      A.C. Green   34  DAL  PF  82  68  32.3  3.0
              1999 4243      A.C. Green   35  DAL  PF  50  35  18.5  2.2
              2000 4756      A.C. Green   36  LAL  PF  82  82  23.5  2.1
              2001 5298      A.C. Green   37  MIA  PF  82   1  17.2  1.8
A.J. Bramlett 2000 4928   A.J. Bramlett   23  CLE   C   8   0   7.6  0.5
A.J. English  1991 182     A.J. English   23  WSB  SG  70  12  20.6  3.6
              1992 576     A.J. English   24  WSB  SG  81   6  20.6  4.5
A.J. Green    2023 18694     A.J. Green   23  MIL  SG  35   1   9.9  1.5
              2024 19349     A.J. Green   24  MIL  SG  56   0  11.0  1.5
              2025 19950     A.J. Green   25  MIL  SG  73   7  22.7  2.5
A.J. Guyton   2001 5216     A.J. Guyton   22  CHI  PG  33   8  19.1  2.4
              2002 5772     A.J. Guyton   23  CHI  PG  45   6  13.5  2.0
              2003 6464     A.J. Guyton   24  GSW  PG   2   0   4.5  0.0

                           FGA    FG%  ...  ORB  DRB  TRB  AST  STL  BLK  TOV  \
Player        Year                     ...
A.C. Green    1991 178     6.6  0.476  ...  2.5  3.8  6.3  0.9  0.7  0.3  1.2
              1992 534     9.8  0.476  ...  3.7  5.6  9.3  1.4  1.1  0.4  1.4
              1993 1004    8.6  0.537  ...  3.5  5.2  8.7  1.4  1.1  0.5  1.4
              1994 1421   11.3  0.502  ...  3.4  5.8  9.2  1.7  0.9  0.5  1.2
              1995 1960    7.5  0.504  ...  2.4  5.8  8.2  1.5  0.7  0.4  1.4
              1996 2522    5.4  0.484  ...  2.0  4.7  6.8  0.9  0.5  0.3  1.0
              1997 3051    5.8  0.483  ...  2.7  5.2  7.9  0.8  0.8  0.2  0.9
              1998 3644    6.5  0.453  ...  2.7  5.5  8.1  1.5  1.0  0.3  0.8
              1999 4243    5.1  0.422  ...  1.6  2.9  4.6  0.5  0.6  0.2  0.4
              2000 4756    4.7  0.447  ...  2.0  4.0  5.9  1.0  0.6  0.2  0.6
              2001 5298    4.0  0.444  ...  1.3  2.5  3.8  0.5  0.4  0.1  0.5
A.J. Bramlett 2000 4928    2.6  0.190  ...  1.5  1.3  2.8  0.0  0.1  0.0  0.4
A.J. English  1991 182     8.2  0.439  ...  0.9  1.2  2.1  2.5  0.4  0.2  1.6
              1992 576    10.4  0.433  ...  0.9  1.2  2.1  1.8  0.4  0.1  1.1
A.J. Green    2023 18694   3.6  0.424  ...  0.2  1.1  1.3  0.6  0.2  0.0  0.3
              2024 19349   3.5  0.423  ...  0.2  1.0  1.1  0.5  0.2  0.1  0.2
              2025 19950   5.8  0.429  ...  0.2  2.1  2.4  1.5  0.5  0.1  0.5
A.J. Guyton   2001 5216    5.8  0.406  ...  0.3  0.8  1.1  1.9  0.3  0.2  0.7
              2002 5772    5.4  0.361  ...  0.3  0.7  1.0  1.8  0.2  0.2  0.8
              2003 6464    2.0  0.000  ...  0.0  0.0  0.0  1.0  0.5  0.0  0.5

                           PF   PTS  Year
Player        Year
A.C. Green    1991 178    1.4   9.1  1991
              1992 534    1.7  13.6  1992
              1993 1004   1.8  12.8  1993
              1994 1421   1.7  14.7  1994
              1995 1960   1.8  11.2  1995
              1996 2522   1.7   7.5  1996
              1997 3051   1.7   7.2  1997
              1998 3644   1.9   7.3  1998
              1999 4243   1.4   4.9  1999
              2000 4756   1.5   5.0  2000
              2001 5298   1.5   4.5  2001
A.J. Bramlett 2000 4928   1.6   1.0  2000
A.J. English  1991 182    1.8   8.8  1991
              1992 576    2.0  10.9  1992
A.J. Green    2023 18694  0.9   4.4  2023
              2024 19349  0.9   4.5  2024
              2025 19950  2.2   7.4  2025
A.J. Guyton   2001 5216   1.1   6.0  2001
              2002 5772   0.5   5.4  2002
              2003 6464   0.0   0.0  2003

[20 rows x 30 columns]

In [295]:
players.index = players.index.droplevel()

In [296]:
players.index = players.index.droplevel()

In [297]:
players

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
178,A.C. Green,27,LAL,PF,82,21,26.4,3.1,6.6,0.476,...,2.5,3.8,6.3,0.9,0.7,0.3,1.2,1.4,9.1,1991
534,A.C. Green,28,LAL,PF,82,53,35.4,4.7,9.8,0.476,...,3.7,5.6,9.3,1.4,1.1,0.4,1.4,1.7,13.6,1992
1004,A.C. Green,29,LAL,PF,82,55,34.4,4.6,8.6,0.537,...,3.5,5.2,8.7,1.4,1.1,0.5,1.4,1.8,12.8,1993
1421,A.C. Green,30,PHO,PF,82,55,34.5,5.7,11.3,0.502,...,3.4,5.8,9.2,1.7,0.9,0.5,1.2,1.7,14.7,1994
1960,A.C. Green,31,PHO,SF,82,52,32.8,3.8,7.5,0.504,...,2.4,5.8,8.2,1.5,0.7,0.4,1.4,1.8,11.2,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5722,Željko Rebrača,29,DET,C,74,4,15.9,2.6,5.1,0.505,...,1.1,2.8,3.9,0.5,0.4,1.0,1.1,2.6,6.9,2002
6208,Željko Rebrača,30,DET,C,30,12,16.3,2.7,4.8,0.552,...,0.9,2.2,3.1,0.3,0.2,0.6,1.0,2.6,6.6,2003
6872,Željko Rebrača,31,ATL,C,24,2,11.4,1.4,3.2,0.442,...,1.0,1.5,2.4,0.3,0.2,0.5,0.7,2.2,3.8,2004
7377,Željko Rebrača,32,LAC,C,58,2,16.0,2.3,4.0,0.568,...,0.8,2.3,3.2,0.4,0.2,0.7,0.8,2.2,5.8,2005
7970,Željko Rebrača,33,LAC,C,29,2,14.2,1.8,3.3,0.542,...,0.4,1.8,2.2,0.3,0.2,0.7,0.8,2.0,4.7,2006

In [298]:
players[players["Player"] == "Greg Anderson"]

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
304,Greg Anderson,26,DEN,PF,68,2,13.6,1.7,4.0,0.430,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
560,Greg Anderson,27,DEN,PF,82,82,34.1,4.7,10.4,0.456,...,4.1,7.4,11.5,1.0,1.1,0.8,2.5,3.2,11.5,1992
1593,Greg Anderson,29,DET,PF,77,47,21.1,2.6,4.8,0.543,...,2.4,5.0,7.4,0.7,0.7,0.9,1.2,3.0,6.4,1994
2200,Greg Anderson,30,ATL,PF,51,0,12.2,1.1,2.0,0.548,...,1.2,2.5,3.7,0.3,0.5,0.6,0.6,2.0,2.9,1995
2802,Greg Anderson,31,SAS,PF,46,7,7.5,0.5,1.0,0.511,...,0.6,1.5,2.2,0.2,0.2,0.5,0.5,1.4,1.2,1996
3196,Greg Anderson,32,SAS,C,82,48,20.2,1.6,3.2,0.496,...,1.9,3.5,5.5,0.4,0.8,0.8,0.9,2.7,3.9,1997
3897,Greg Anderson,33,ATL,C,50,0,8.0,0.7,1.6,0.444,...,0.8,1.6,2.4,0.3,0.4,0.2,0.3,1.7,1.8,1998

In [299]:
combined = players.merge(mvps, how="outer", on=["Player", "Year"])

In [300]:
combined.head(5)

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,27,LAL,PF,82,21,26.4,3.1,6.6,0.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,NaN,NaN,NaN
1,A.C. Green,28,LAL,PF,82,53,35.4,4.7,9.8,0.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,NaN,NaN,NaN
2,A.C. Green,29,LAL,PF,82,55,34.4,4.6,8.6,0.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,NaN,NaN,NaN
3,A.C. Green,30,PHO,PF,82,55,34.5,5.7,11.3,0.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,NaN,NaN,NaN
4,A.C. Green,31,PHO,SF,82,52,32.8,3.8,7.5,0.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,NaN,NaN,NaN

In [301]:
combined[combined["Pts Won"] > 0]

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
229,Al Jefferson,29,CHA,C,73,73,35.0,9.6,18.8,0.509,...,2.1,0.9,1.1,1.7,2.4,21.8,2014,34.0,1250.0,0.027
394,Allen Iverson,21,PHI,PG,76,74,40.1,8.2,19.8,0.416,...,7.5,2.1,0.3,4.4,3.1,23.5,1997,1.0,1150.0,0.001
396,Allen Iverson,23,PHI,SG,48,48,41.5,9.1,22.0,0.412,...,4.6,2.3,0.1,3.5,2.0,26.8,1999,319.0,1180.0,0.270
397,Allen Iverson,24,PHI,SG,70,70,40.8,10.4,24.8,0.421,...,4.7,2.1,0.1,3.3,2.3,28.4,2000,132.0,1210.0,0.109
398,Allen Iverson,25,PHI,SG,71,71,42.0,10.7,25.5,0.420,...,4.6,2.5,0.3,3.3,2.1,31.1,2001,1121.0,1240.0,0.904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15801,Vince Carter,23,TOR,SF,82,82,38.1,9.6,20.7,0.465,...,3.9,1.3,1.1,2.2,3.2,25.7,2000,51.0,1210.0,0.042
15802,Vince Carter,24,TOR,SF,75,75,39.7,10.2,22.1,0.460,...,3.9,1.5,1.1,2.2,2.7,27.6,2001,7.0,1240.0,0.006
15806,Vince Carter,28,NJN,SF,77,76,36.7,9.0,20.0,0.452,...,4.2,1.4,0.6,2.2,3.2,24.5,2005,3.0,1270.0,0.002
16210,Yao Ming,23,HOU,C,82,82,32.8,6.5,12.5,0.522,...,1.5,0.3,1.9,2.5,3.3,17.5,2004,1.0,1230.0,0.001
16215,Yao Ming,28,HOU,C,77,77,33.6,7.4,13.4,0.548,...,1.8,0.4,1.9,3.0,3.3,19.7,2009,1.0,1210.0,0.001

In [302]:
combined[["Pts Won", "Pts Max", "Share"]] = combined[["Pts Won", "Pts Max", "Share"]].fillna(0)

In [303]:
combined

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,27,LAL,PF,82,21,26.4,3.1,6.6,0.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0
1,A.C. Green,28,LAL,PF,82,53,35.4,4.7,9.8,0.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0
2,A.C. Green,29,LAL,PF,82,55,34.4,4.6,8.6,0.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0
3,A.C. Green,30,PHO,PF,82,55,34.5,5.7,11.3,0.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0
4,A.C. Green,31,PHO,SF,82,52,32.8,3.8,7.5,0.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16377,Željko Rebrača,29,DET,C,74,4,15.9,2.6,5.1,0.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,0.0,0.0,0.0
16378,Željko Rebrača,30,DET,C,30,12,16.3,2.7,4.8,0.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,0.0,0.0,0.0
16379,Željko Rebrača,31,ATL,C,24,2,11.4,1.4,3.2,0.442,...,0.3,0.2,0.5,0.7,2.2,3.8,2004,0.0,0.0,0.0
16380,Željko Rebrača,32,LAC,C,58,2,16.0,2.3,4.0,0.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,0.0,0.0,0.0
16381,Željko Rebrača,33,LAC,C,29,2,14.2,1.8,3.3,0.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,0.0,0.0,0.0

In [304]:
teams = pd.read_csv("teams.csv")

In [305]:
teams = teams[~teams["W"].str.contains("Division")]

In [306]:
teams["Team"] = teams["Team"].str.replace("*","",regex=False)

In [307]:
teams.head(30)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
7,7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks
10,10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks
11,11,41,41,.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers
12,12,33,49,.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers
13,13,26,56,.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets
15,1,55,27,.671,—,107.1,102.6,4.30,1991,San Antonio Spurs
16,2,54,28,.659,1.0,104.0,100.7,3.18,1991,Utah Jazz
17,3,52,30,.634,3.0,106.7,103.2,3.27,1991,Houston Rockets
18,4,31,51,.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic
19,5,29,53,.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves
20,6,28,54,.341,27.0,99.9,104.5,-4.27,1991,Dallas Mavericks
21,7,20,62,.244,35.0,119.9,130.8,-10.31,1991,Denver Nuggets
23,9,63,19,.768,—,114.7,106.0,8.47,1991,Portland Trail Blazers
24,10,58,24,.707,5.0,106.3,99.6,6.73,1991,Los Angeles Lakers
25,11,55,27,.671,8.0,114.0,107.5,6.49,1991,Phoenix Suns
26,12,44,38,.537,19.0,116.6,115.0,1.72,1991,Golden State Warriors
27,13,41,41,.500,22.0,106.6,105.4,1.31,1991,Seattle SuperSonics
28,14,31,51,.378,32.0,103.5,107.0,-3.16,1991,Los Angeles Clippers
29,15,25,57,.305,38.0,96.7,103.5,-6.27,1991,Sacramento Kings
30,0,51,31,.622,—,106.6,103.0,3.41,1992,Boston Celtics
31,1,51,31,.622,—,101.6,97.7,3.67,1992,New York Knicks
32,2,40,42,.488,11.0,105.4,107.1,-1.54,1992,New Jersey Nets

In [308]:
nicknames = {}

with open("nicknames.csv") as f:
    lines = f.readlines()
    for line in lines[1:]:
        abbrev,name = line.replace("\n","").split(",")
        nicknames[abbrev] = name

In [309]:
combined["Teams"] = combined["Team"].map(nicknames)
combined["Tm"] = combined["Team"]
del combined["Team"]
combined["Team"] = combined["Teams"]
del combined["Teams"]

In [310]:
combined

,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,3P,...,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share,Tm,Team
0,A.C. Green,27,PF,82,21,26.4,3.1,6.6,0.476,0.1,...,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0,LAL,Los Angeles Lakers
1,A.C. Green,28,PF,82,53,35.4,4.7,9.8,0.476,0.1,...,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0,LAL,Los Angeles Lakers
2,A.C. Green,29,PF,82,55,34.4,4.6,8.6,0.537,0.2,...,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0,LAL,Los Angeles Lakers
3,A.C. Green,30,PF,82,55,34.5,5.7,11.3,0.502,0.1,...,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0,PHO,Phoenix Suns
4,A.C. Green,31,SF,82,52,32.8,3.8,7.5,0.504,0.5,...,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0,PHO,Phoenix Suns
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16377,Željko Rebrača,29,C,74,4,15.9,2.6,5.1,0.505,0.0,...,1.0,1.1,2.6,6.9,2002,0.0,0.0,0.0,DET,Detroit Pistons
16378,Željko Rebrača,30,C,30,12,16.3,2.7,4.8,0.552,0.0,...,0.6,1.0,2.6,6.6,2003,0.0,0.0,0.0,DET,Detroit Pistons
16379,Željko Rebrača,31,C,24,2,11.4,1.4,3.2,0.442,0.0,...,0.5,0.7,2.2,3.8,2004,0.0,0.0,0.0,ATL,Atlanta Hawks
16380,Željko Rebrača,32,C,58,2,16.0,2.3,4.0,0.568,0.0,...,0.7,0.8,2.2,5.8,2005,0.0,0.0,0.0,LAC,Los Angeles Clippers
16381,Željko Rebrača,33,C,29,2,14.2,1.8,3.3,0.542,0.0,...,0.7,0.8,2.0,4.7,2006,0.0,0.0,0.0,LAC,Los Angeles Clippers

In [311]:
stats = combined.merge(teams, how="outer", on=["Team","Year"])

In [312]:
stats

,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,3P,...,Tm,Team,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,27,PF,82,21,26.4,3.1,6.6,0.476,0.1,...,LAL,Los Angeles Lakers,10,58,24,.707,5.0,106.3,99.6,6.73
1,Byron Scott,29,SG,82,82,32.1,6.1,12.8,0.477,0.9,...,LAL,Los Angeles Lakers,10,58,24,.707,5.0,106.3,99.6,6.73
2,Elden Campbell,22,PF,52,0,7.3,1.1,2.4,0.455,0.0,...,LAL,Los Angeles Lakers,10,58,24,.707,5.0,106.3,99.6,6.73
3,Irving Thomas,25,PF,26,0,4.2,0.7,1.9,0.340,0.0,...,LAL,Los Angeles Lakers,10,58,24,.707,5.0,106.3,99.6,6.73
4,James Worthy,29,SF,78,74,38.6,9.2,18.7,0.492,0.3,...,LAL,Los Angeles Lakers,10,58,24,.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16377,Spencer Hawes,28,PF,54,1,14.8,2.5,5.1,0.484,0.5,...,MIL,Milwaukee Bucks,7,42,40,.512,9.0,103.6,103.8,-0.45
16378,Steve Novak,33,PF,8,0,2.8,0.3,0.9,0.286,0.1,...,MIL,Milwaukee Bucks,7,42,40,.512,9.0,103.6,103.8,-0.45
16379,Terrence Jones,25,PF,54,12,23.5,4.3,9.1,0.470,0.4,...,MIL,Milwaukee Bucks,7,42,40,.512,9.0,103.6,103.8,-0.45
16380,Thon Maker,19,C,57,34,9.9,1.5,3.2,0.459,0.5,...,MIL,Milwaukee Bucks,7,42,40,.512,9.0,103.6,103.8,-0.45
16381,Tony Snell,25,SG,80,80,29.2,3.1,6.8,0.455,1.8,...,MIL,Milwaukee Bucks,7,42,40,.512,9.0,103.6,103.8,-0.45

In [314]:
del stats["Unnamed: 0"]

In [316]:
stats.dtypes

Player      object
Age          int64
Pos         object
G            int64
GS           int64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Tm          object
Team        object
W           object
L           object
W/L%        object
GB          object
PS/G        object
PA/G        object
SRS         object
dtype: object

In [317]:
stats = stats.apply(pd.to_numeric, errors="ignore")

In [318]:
stats.dtypes

Player      object
Age          int64
Pos         object
G            int64
GS           int64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Tm          object
Team        object
W            int64
L            int64
W/L%       float64
GB          object
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [321]:
stats["GB"] = stats["GB"].str.replace("—", "0")

In [322]:
stats["GB"].unique()

array(['5.0', '14.0', '23.0', '7.0', '0', '40.0', '42.0', '18.0', '6.0',
       '24.0', '26.0', '16.0', '37.0', '29.0', '21.0', '28.0', '13.0',
       '31.0', '25.0', '8.0', '19.0', '3.0', '11.0', '1.0', '17.0',
       '15.0', '9.0', '2.0', '35.0', '20.0', '41.0', '12.0', '50.0',
       '10.0', '30.0', '34.0', '4.0', '1.5', '22.0', '51.0', '36.0',
       '43.0', '39.0', '18.5', '48.0', '46.0', '10.5', '32.0', '38.0',
       '27.0', '33.0', '21.5', '45.0', '22.5', '25.5', '3.5', '20.5',
       '11.5', '44.0', '52.0', '56.0', '2.5', '12.5', '47.0', '32.5',
       '4.5'], dtype=object)

In [324]:
stats["GB"] = pd.to_numeric(stats["GB"])

In [325]:
stats.dtypes

Player      object
Age          int64
Pos         object
G            int64
GS           int64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Tm          object
Team        object
W            int64
L            int64
W/L%       float64
GB         float64
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [326]:
stats.to_csv("player_mvp_stats.csv")

In [328]:
highest_scoring = stats[stats["G"] > 65].sort_values("PTS", ascending=False).head(10)

In [329]:
highest_scoring

,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,3P,...,Share,Tm,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
11230,James Harden,29,PG,78,78,36.8,10.8,24.5,0.442,4.8,...,0.768,HOU,Houston Rockets,53,29,0.646,0.0,113.9,109.1,4.96
1369,Kobe Bryant,27,SG,80,80,41.0,12.2,27.2,0.450,2.3,...,0.386,LAL,Los Angeles Lakers,45,37,0.549,9.0,99.4,96.9,2.53
11247,James Harden,30,SG,68,68,36.5,9.9,22.3,0.444,4.4,...,0.363,HOU,Houston Rockets,44,28,0.611,0.0,117.8,114.8,3.13
365,Luka Dončić,24,PG,70,70,37.5,11.5,23.6,0.487,4.1,...,0.572,DAL,Dallas Mavericks,50,32,0.610,0.0,117.9,115.6,2.30
15976,Joel Embiid,28,C,66,66,34.6,11.0,20.1,0.548,1.0,...,0.915,PHI,Philadelphia 76ers,54,28,0.659,3.0,115.2,110.9,4.37
5344,Allen Iverson,30,PG,72,72,43.1,11.3,25.3,0.447,1.0,...,0.001,PHI,Philadelphia 76ers,38,44,0.463,11.0,99.4,101.3,-2.10
1580,Shai Gilgeous-Alexander,26,PG,76,76,34.2,11.3,21.8,0.519,2.1,...,0.000,OKC,Oklahoma City Thunder,68,14,0.829,0.0,120.5,107.6,12.70
11548,Michael Jordan,29,SG,78,78,39.3,12.7,25.7,0.495,1.0,...,0.577,CHI,Chicago Bulls,57,25,0.695,0.0,105.2,98.9,6.19
344,Luka Dončić,23,PG,66,66,36.2,10.9,22.0,0.496,2.8,...,0.010,DAL,Dallas Mavericks,38,44,0.463,13.0,114.2,114.1,-0.14
8000,Tracy McGrady,23,SG,75,74,39.4,11.1,24.2,0.457,2.3,...,0.359,ORL,Orlando Magic,42,40,0.512,7.0,98.5,98.4,-0.39

In [330]:
stats.groupby("Year").apply(lambda x: x.sort_values("PTS", ascending = False).head(1))

,,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,3P,...,Share,Tm,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
Year,,,,,,,,,,,,,,,,,,,,,,
1991,11522,Michael Jordan,27,SG,82,82,37.0,12.1,22.4,0.539,0.4,...,0.928,CHI,Chicago Bulls,61,21,0.744,0.0,110.0,101.0,8.57
1992,11535,Michael Jordan,28,SG,80,80,38.8,11.8,22.7,0.519,0.3,...,0.938,CHI,Chicago Bulls,67,15,0.817,0.0,109.9,99.5,10.07
1993,11548,Michael Jordan,29,SG,78,78,39.3,12.7,25.7,0.495,1.0,...,0.577,CHI,Chicago Bulls,57,25,0.695,0.0,105.2,98.9,6.19
1994,10159,David Robinson,28,C,80,80,40.5,10.5,20.7,0.507,0.1,...,0.723,SAS,San Antonio Spurs,55,27,0.671,3.0,100.0,94.8,5.05
1995,8497,Shaquille O'Neal,22,C,79,79,37.0,11.8,20.2,0.583,0.0,...,0.576,ORL,Orlando Magic,57,25,0.695,0.0,110.9,103.8,6.44
1996,12143,Michael Jordan,32,SG,82,82,37.7,11.2,22.6,0.495,1.4,...,0.986,CHI,Chicago Bulls,72,10,0.878,0.0,105.2,92.9,11.80
1997,12157,Michael Jordan,33,SG,82,82,37.9,11.2,23.1,0.486,1.4,...,0.832,CHI,Chicago Bulls,69,13,0.841,0.0,103.1,92.3,10.70
1998,12171,Michael Jordan,34,SG,82,82,38.8,10.7,23.1,0.465,0.4,...,0.934,CHI,Chicago Bulls,62,20,0.756,0.0,96.7,89.6,7.24
1999,1255,Allen Iverson,23,SG,48,48,41.5,9.1,22.0,0.412,1.2,...,0.270,PHI,Philadelphia 76ers,28,22,0.560,5.0,89.7,87.6,2.56
2000,143,Shaquille O'Neal,27,C,79,79,40.0,12.1,21.1,0.574,0.0,...,0.998,LAL,Los Angeles Lakers,67,15,0.817,0.0,100.8,92.3,8.41
2001,1286,Allen Iverson,25,SG,71,71,42.0,10.7,25.5,0.420,1.4,...,0.904,PHI,Philadelphia 76ers,56,26,0.683,0.0,94.7,90.4,3.64
2002,1302,Allen Iverson,26,SG,60,59,43.7,11.1,27.8,0.398,1.3,...,0.023,PHI,Philadelphia 76ers,43,39,0.524,9.0,91.0,89.4,1.27
2003,8000,Tracy McGrady,23,SG,75,74,39.4,11.1,24.2,0.457,2.3,...,0.359,ORL,Orlando Magic,42,40,0.512,7.0,98.5,98.4,-0.39
2004,8013,Tracy McGrady,24,SG,67,67,39.9,9.7,23.4,0.417,2.6,...,0.000,ORL,Orlando Magic,21,61,0.256,26.0,94.0,101.1,-7.25
2005,1349,Allen Iverson,29,PG,75,75,42.3,10.3,24.2,0.424,1.4,...,0.189,PHI,Philadelphia 76ers,43,39,0.524,2.0,99.1,99.9,-1.07
2006,1369,Kobe Bryant,27,SG,80,80,41.0,12.2,27.2,0.450,2.3,...,0.386,LAL,Los Angeles Lakers,45,37,0.549,9.0,99.4,96.9,2.53
2007,1383,Kobe Bryant,28,SG,77,77,40.8,10.6,22.8,0.463,1.8,...,0.404,LAL,Los Angeles Lakers,42,40,0.512,19.0,103.3,103.4,0.24
2008,6591,LeBron James,23,SF,75,74,40.4,10.6,21.9,0.484,1.5,...,0.348,CLE,Cleveland Cavaliers,45,37,0.549,14.0,96.4,96.7,-0.53
2009,15400,Dwyane Wade,27,SG,79,79,38.6,10.8,22.0,0.491,1.1,...,0.562,MIA,Miami Heat,43,39,0.524,16.0,98.3,98.0,0.49
2010,10329,Kevin Durant,21,SF,82,82,39.5,9.7,20.3,0.476,1.6,...,0.495,OKC,Oklahoma City Thunder,50,32,0.610,3.0,101.5,98.0,3.55
2011,14639,Kevin Durant,22,SF,78,78,38.9,9.1,19.7,0.462,1.9,...,0.157,OKC,Oklahoma City Thunder,55,27,0.671,0.0,104.8,101.0,3.81
2012,15633,Kevin Durant,23,SF,66,66,38.6,9.7,19.7,0.496,2.0,...,0.735,OKC,Oklahoma City Thunder,47,19,0.712,0.0,103.1,96.9,6.44
2013,6264,Carmelo Anthony,28,PF,67,67,37.0,10.0,22.2,0.449,2.3,...,0.393,NYK,New York Knicks,54,28,0.659,0.0,100.0,95.7,3.73
2014,7429,Kevin Durant,25,SF,81,81,38.5,10.5,20.8,0.503,2.4,...,0.986,OKC,Oklahoma City Thunder,59,23,0.720,0.0,106.2,99.8,6.66
2015,7452,Russell Westbrook,26,PG,67,67,34.4,9.4,22.0,0.426,1.3,...,0.271,OKC,Oklahoma City Thunder,45,37,0.549,6.0,104.0,101.8,2.47
2016,6640,Stephen Curry,27,PG,79,79,34.2,10.2,20.2,0.504,5.1,...,1.000,GSW,Golden State Warriors,73,9,0.890,0.0,114.9,104.1,10.38
2017,7481,Russell Westbrook,28,PG,81,81,34.6,10.2,24.0,0.425,2.5,...,0.879,OKC,Oklahoma City Thunder,47,35,0.573,4.0,106.6,105.8,1.14
2018,1185,James Harden,28,SG,72,72,35.4,9.0,20.1,0.449,3.7,...,0.955,HOU,Houston Rockets,65,17,0.793,0.0,112.4,103.9,8.21
2019,11230,James Harden,29,PG,78,78,36.8,10.8,24.5,0.442,4.8,...,0.768,HOU,Houston Rockets,53,29,0.646,0.0,113.9,109.1,4.96
2020,11247,James Harden,30,SG,68,68,36.5,9.9,22.3,0.444,4.4,...,0.363,HOU,Houston Rockets,44,28,0.611,0.0,117.8,114.8,3.13
2021,4435,Stephen Curry,32,PG,63,63,34.2,10.4,21.7,0.482,5.3,...,0.449,GSW,Golden State Warriors,39,33,0.542,12.0,113.7,112.7,1.10
2022,1058,Joel Embiid,27,C,68,68,33.8,9.8,19.6,0.499,1.4,...,0.706,PHI,Philadelphia 76ers,51,31,0.622,0.0,109.9,107.3,2.57
2023,15976,Joel Embiid,28,C,66,66,34.6,11.0,20.1,0.548,1.0,...,0.915,PHI,Philadelphia 76ers,54,28,0.659,3.0,115.2,110.9,4.37
2024,14607,Joel Embiid,29,C,39,39,33.6,11.5,21.8,0.529,1.4,...,0.000,PHI,Philadelphia 76ers,47,35,0.573,17.0,114.6,111.5,2.51
2025,1580,Shai Gilgeous-Alexander,26,PG,76,76,34.2,11.3,21.8,0.519,2.1,...,0.000,OKC,Oklahoma City Thunder,68,14,0.829,0.0,120.5,107.6,12.70

In [332]:
stats.corr()["Share"]

ValueError: could not convert string to float: 'A.C. Green'